### ISSUE TITLE
Localise background images

### ISSUE THREAD

**Issue by HarishTeens** [HarishTeens/yelpcamp#2]
The homepage has a slideshow animation , the URLs are referenced to web download the images locally and link them

**Comment by shivambachhety** [comment]
Kindly explain the contribution that needs to be done.

**Comment by HarishTeens** [comment]
https://github.com/HarishTeens/yelpcamp/blob/25f7b8069484982a8a31bd48ad0bf75fafbe99a6/public/stylesheets/landing.css#L38

This is line in .css which is responsible for loading the background slideshow in the landing page. 
instead of fetching the image from the i.imgur.com , it should be fetching the images stored locally in the folder

**Comment by ikayz** [comment]
@HarishTeens can I take this on?

**Comment by HarishTeens** [comment]
@shivambachhety  had requested before , if he doesnt sure you can go on @ikayz

**Comment by ikayz** [comment]
@HarishTeens sure thing

**Comment by HarishTeens** [comment]
work on this issue if you want to , I just created this for you [issue](https://github.com/HarishTeens/yelpcamp/issues/6)

**Comment by shivambachhety** [comment]
@HarishTeens thanks, I am working on the issue. What path to give to local images folder?

**Comment by HarishTeens** [comment]
@shivambachhety Inside public create a folder /images and add those here

**Comment by shivambachhety** [comment]
Done, Kindly review https://github.com/shivambachhety/yelpcamp/pull/2/commits/1b0c46ae4268b567be3af43fbf9fbd05d313f9f0

**Comment by Askat08** [comment]
Hi @HarishTeens. Is there anything similar to this issue, where i can practice my skills?

**Comment by ikayz** [comment]
@HarishTeens thanks on it

**Comment by himanshunikhare-zz** [comment]
Can I work on this issue?

**Comment by HarishTeens** [comment]
Sorry guys , I've merged the PR to this issue , don't worry I'll be updating more beginner issues to my projects
