### ISSUE TITLE
actual comment  date

### ISSUE THREAD

**Issue by HarishTeens** [HarishTeens/yelpcamp#3]
https://github.com/HarishTeens/yelpcamp/blob/25f7b8069484982a8a31bd48ad0bf75fafbe99a6/views/campgrounds/show.ejs#L40

Display the actual date when the comment was made

**Comment by thesanjeevsharma** [comment]
Hello, I am working on this issue!

**Comment by HarishTeens** [comment]
Great . Do give a PR once done 🎉

**Comment by thebishaldeb** [comment]
Want to work on it
